### ISSUE TITLE
Does It support the Wifi bedside lamp?

### ISSUE THREAD

**Issue by ghost** [vieira/homebridge-yeelight-wifi#10]
Does It support the Wifi bedside lamp?

**Comment by vieira** [comment]
Hello @malmentm,

If it is the Wi-Fi version it should work, but I cannot tell for sure because I don't own one and never tested specifically with the bedside lamp.

Are you having any problems or just considering before buying?

Thanks!

**Comment by ghost** [comment]
Just consider before buying 💃

**Comment by ghost** [comment]
@vieira Should the Yeelight JIAOYUE 650 also work? It got two separate lighting zones so it might show up as two separate lights?

**Comment by Nastras** [comment]
Hello, I just wanted to say that I have tested your plugin with the Bedside Lamp wifi. The lamp can be controlled.

But there is a big problem, your plugin does not work with multiple homebridges. Once your plugin is started, this error will be reported in the journal of every Homebridge. Can you fix that?


Apr 11 12:00:20 HomeBridgeServer homebridge[566]: [2018-4-11 12:00:19] [Yeelight] doing a round of proactive search for known devices.
Apr 11 12:00:20 HomeBridgeServer homebridge[566]: events.js:165
Apr 11 12:00:20 HomeBridgeServer homebridge[566]:       throw er; // Unhandled 'error' event
Apr 11 12:00:20 HomeBridgeServer homebridge[566]:       ^
Apr 11 12:00:20 HomeBridgeServer homebridge[566]: Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data
Apr 11 12:00:20 HomeBridgeServer homebridge[566]:     at Socket.onListenError (dgram.js:362:22)
Apr 11 12:00:20 HomeBridgeServer homebridge[566]:     at Object.onceWrapper (events.js:272:13)
Apr 11 12:00:20 HomeBridgeServer homebridge[566]:     at Socket.emit (events.js:180:13)
Apr 11 12:00:20 HomeBridgeServer homebridge[566]:     at _handle.lookup (dgram.js:267:14)
Apr 11 12:00:20 HomeBridgeServer homebridge[566]:     at process._tickCallback (internal/process/next_tick.js:178:19)
Apr 11 12:00:20 HomeBridgeServer homebridge[566]:     at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
Apr 11 12:00:20 HomeBridgeServer homebridge[566]:     at startup (internal/bootstrap/node.js:201:19)
Apr 11 12:00:20 HomeBridgeServer homebridge[566]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
Apr 11 12:00:20 HomeBridgeServer homebridge[566]: Emitted 'error' event at:
Apr 11 12:00:20 HomeBridgeServer homebridge[566]:     at Socket.onListenError (dgram.js:362:8)
Apr 11 12:00:20 HomeBridgeServer homebridge[566]:     at Object.onceWrapper (events.js:272:13)
Apr 11 12:00:20 HomeBridgeServer homebridge[566]:     [... lines matching original stack trace ...]
Apr 11 12:00:20 HomeBridgeServer systemd[1]: homebridge-yeelight-wifi.service: Main process exited, code=exited, status=1/FAILURE
Apr 11 12:00:20 HomeBridgeServer systemd[1]: homebridge-yeelight-wifi.service: Unit entered failed state.
Apr 11 12:00:20 HomeBridgeServer systemd[1]: homebridge-yeelight-wifi.service: Failed with result 'exit-code'.
Apr 11 12:00:30 HomeBridgeServer systemd[1]: homebridge-yeelight-wifi.service: Service hold-off time over, scheduling restart.
Apr 11 12:00:30 HomeBridgeServer systemd[1]: Stopped homebridge-yeelight-wifi.
Apr 11 12:00:30 HomeBridgeServer systemd[1]: Started homebridge-yeelight-wifi.

**Comment by Nastras** [comment]
One more problem, your plugin adds the same lamp several times. Now I have four ghost lamps that I can not get deleted -.-

Really bad.

**Comment by vieira** [comment]
Hello @Nastras,

Thanks for letting me know.

I will try to reproduce the problem by running two instances of homebridge. 

Are you running both on the same machine?

**Comment by Nastras** [comment]
I have 21 Homebridgs instances all running on one system. So far I have not had the problem with any plugin.

**Comment by Nastras** [comment]
Hey @vieira

the ghost devices disappeared after a reboot. Luckily!
But I can not explain how it happened. The bug with multiple instances is available as usual.

**Comment by Razeeer** [comment]
@vieira I have the same Problem with multiple Instances with your Plugin how @Nastras 
I found this a similar error is described here. Maybe it helps you to fix it?
https://github.com/oznu/homebridge-config-ui-x/issues/75

Could you reproduce bug?

**Comment by vieira** [comment]
@Razeeer, Yes I was able to reproduce it. However to write a proper fix I would like to understand the use case of running multiple instances of the plugin in the same machine, otherwise I may fix the error but still break your use-case.

Can you shed some light?

Thanks!!

**Comment by Razeeer** [comment]
You have to imagine that for each plugin example homebridge-hue, homebridge-cmdswitch and your plugin homebridge-yeelight-wifi your own Homebridge instance is started which creates a bridge with devices for home kit.
It will start a separate systemd sevice for each plugin.

Your plugin will run only once on the system for all yeelight devices in this case.

The great advantage is that each plugin runs separately from each other and not all devices are affected by an error but only one instance at a time.

The problem what Nastras has described is that your plugin all other instances that are also started stops with the bug from above.

I hope it is understandable for you now?

**Comment by vieira** [comment]
Hello @Razeeer,

Thanks for explaining. Yes, I think I am starting to understand the idea.

Each instance has its own configuration but they all share the same homebridge installation and plugins? Is that it? 

If so an option to disable the plugin would solve the issue as it would only run on its instance, and not on all other instances, right?

Many thanks!

**Comment by Razeeer** [comment]
That's right, all instances access the same plugins found in node_modules and a Homebridge installation. Each instance has its own Config.json.

Your plugin starts with each instance and blocks all other instances.
No other plugin I use behaves like this.

**Comment by Razeeer** [comment]
Maybe this will help you here:

https://github.com/nfarina/homebridge/issues/1160

or this

https://github.com/joe-ng/homebridge-dyson-link/issues/17

**Comment by vieira** [comment]
Hello @Razeeer,

Ok, I think I understand now.

I will write a fix and let you know. If you can give it a try over the weekend I will publish a new version then.

**Comment by Razeeer** [comment]
Thats great!

**Comment by vieira** [comment]
Hello @Nastras @Razeeer 

Can you please test if #15 fixes your issue?

Thanks!

**Comment by vieira** [comment]
Closed #15 in favour of #19 which should properly fix the issue.

**Comment by vieira** [comment]
This was fixed by homebridge on nfarina/homebridge#1880
