### ISSUE TITLE
Yeelight Magic Light (Light Triangle Panels)

### ISSUE THREAD

**Issue by Myth0zz** [vieira/homebridge-yeelight-wifi#101]
Hello, 

I just bought this: https://us.yeelight.com/shop/yeelight-smart-led-light-panels/ 

Model: yeelink.light.plate2 

However when I turn on LAN Control in Yeelight app my whole HOOBS collapses. When I turn off LAN control it works OK from the Yeelight, HOOBS is back working, but I cannot use this panel via homekit. 

Perhaps it's new and you need to implement support for it? Is there something you can do? 

It would be great if you could solve this issue. 

Nick

**Comment by Myth0zz** [comment]
THis is what my log says when the service shuts down: [HOOBS 1B3C@plate2-83e6e5@@On] characteristic value expected boolean and received undefined

[yeelight] Received advertisement from e79c5e.
16/11/2021, 19:59:05 [yeelight] Device ceiling3-e79c5e supports moonlight mode
16/11/2021, 19:59:05 [yeelight] Device ceiling3-e79c5e supports brightness
16/11/2021, 19:59:05 [yeelight] Device ceiling3-e79c5e supports color temperature
16/11/2021, 19:59:05 [HOOBS 1B3C@ceiling3-e79c5e@@On] characteristic value expected boolean and received undefined
16/11/2021, 19:59:05 [yeelight] Initialized device  (192.168.152.103:55443).
16/11/2021, 19:59:05 [yeelight] Received advertisement from e79c5e.
16/11/2021, 19:59:05 [yeelight] Received advertisement from bead93.
16/11/2021, 19:59:05 [yeelight] Device ceiling3-bead93 supports moonlight mode
16/11/2021, 19:59:05 [yeelight] Device ceiling3-bead93 supports brightness
16/11/2021, 19:59:05 [yeelight] Device ceiling3-bead93 supports color temperature
16/11/2021, 19:59:05 [yeelight] Initialized device  (192.168.152.237:55443).
16/11/2021, 19:59:05 [HOOBS 1B3C@ceiling3-bead93@@On] characteristic value expected boolean and received undefined

**Comment by vieira** [comment]
Should be fixed in 2.4.0. 👍
