### ISSUE TITLE
Yeelight LED Screen Light bar Pro

### ISSUE THREAD

**Issue by alxrguz** [vieira/homebridge-yeelight-wifi#102]
Good afternoon, first of all I would like to say a huge thank you for your work!

I recently bought a monitor lamp and dubbed it in Homebridge using your module. 
Detail info about lamp: 
link - https://aliexpress.com/item/1005001844087236.html
model - yeelink.light.lamp15

The lamp has 2 light sources, RGB backlighting (background lighting) and a main led light that can only change the temperature. HomeKit only displays the main light and a switch that does not affect: [HomeKit Screenshot](https://user-images.githubusercontent.com/55058570/144391489-db6452ee-76d0-42be-9ff1-eb105ba65c90.PNG)

I would like to have 2 control sliders: 1 for the main light and 1 for the background light. 

Can I somehow tweak the config file for this device? Or will you have to add its support to the module?

**Comment by Marfre888** [comment]
Nice to see that at least this plugin partially works. Do you think it would work with the Basic Yeelight Monitor Light (ie: not the Pro version)?

Would be great if it could be fully supported.

**Comment by alxrguz** [comment]
> Nice to see that at least this plugin partially works. Do you think it would work with the Basic Yeelight Monitor Light (ie: not the Pro version)?
> 
> Would be great if it could be fully supported.

As far as I know, this lamp does not connect to mi home, most likely it does not have a WiFi module

**Comment by Marfre888** [comment]
> > Nice to see that at least this plugin partially works. Do you think it would work with the Basic Yeelight Monitor Light (ie: not the Pro version)?
> > Would be great if it could be fully supported.
> 
> As far as I know, this lamp does not connect to mi home, most likely it does not have a WiFi module

Weird, reading the description of the two products the only difference seems to be the lack of Raze/overwolf support, but trying to confirm it will work

**Comment by samwzlim** [comment]
@alxrguz I am thinking of getting the Yeelight LED Screen Light Bar Pro and hooking it up to homebridge as well for the adaptive lighting feature. How well does the adaptive lighting feature work on this particular model?

**Comment by alxrguz** [comment]
@samwzlim good afternoon, adaptive lighting works great, only problems with LED backlighting, it will only have to be controlled from the mi home app

**Comment by samwzlim** [comment]
Just bought the Yeelight Screen Light Bar Pro as well and can confirm there are 2 control sliders; 1 for the main light and 1 for the ambient backlight, however only the main light can be adjusted while the ambient backlight is unable to.

**Comment by Marfre888** [comment]
@vieira Would it be possible to offer support for this? Or is it too time consuming?

**Comment by vieira** [comment]
Initial support for controlling power, brightness and the color of the backlight (also known as ambilight) of devices that have it is now in 3.0.0-beta.0. 🎉

As I don't have a lamp that supports it I would be relying on you to let me know if everything is working as expected!

Please note that 3.x requires node >= 16.16 and homebridge >= 1.3.0.
