### ISSUE TITLE
Can't find the light if firewall started

### ISSUE THREAD

**Issue by yugu91** [vieira/homebridge-yeelight-wifi#106]
Hi guys, As title, when the firewalld service stop that the lights will be found
System is centos8, which ports will be use?

**Comment by vieira** [comment]
Hello, for homebridge in general you will need `udp/5353` used for avahi/bonjour, whatever port you configure in `config.json` as `bridge.port`, in the example `config.json` it's `tcp/51828` and for the plugin specifically `udp/1982` used for multicast communication with the lamps. Unicast communication with each lamp is done by connecting to `tcp/55443` of the corresponding lamp.
