### ISSUE TITLE
Mi Smart Led Bulb Essential (yeelink.light.color5, MJDPL01YL)

### ISSUE THREAD

**Issue by EralpN** [vieira/homebridge-yeelight-wifi#108]
When I use it with this plugin I get errors below.

[homebridge-yeelight-wifi] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[homebridge-yeelight-wifi] This plugin generated a warning from the characteristic 'Color Temperature': characteristic was supplied illegal value: number 499 exceeded maximum of 370. See https://git.io/JtMGR for more info.

*****
This command;
"miiocli yeelight --ip 192.168.*.* --token *************************** status"
Gives me,

Name: 
Update default on change: True
Delay in minute before off: 0
Music mode: False
Developer mode: True
Main light
   Power: True
   Brightness: 20
   Color mode: RGB
   RGB: (205, 133, 63)
   Color flowing mode: False

*****
Below are the commands that I know that can be given to this bulb;
info Get miIO protocol information from the device. 
off Power off. 
on Power on. 
raw_command Send a raw command to the device. 
set_brightness Set brightness. 
set_color_temp Set color temp in kelvin. 
set_default Set current state as default. 
set_developer_mode Enable or disable the developer mode. 
set_name Set an internal name for the bulb. 
set_rgb Set color in RGB. 
set_save_state_on_change Enable or disable saving the state on changes. 
status Retrieve properties.
toggle Toggle bulb state.

Above commands require miio (https://python-miio.readthedocs.io/)

*****
This bulb has a color temperature range of 1700k - 6500k
I hope you integrate this device to your plugin. Thanks for your hardwork.

**Comment by vieira** [comment]
Support for the full range of color temperature supported by `color5` should now be present in 3.0.0-beta.0. 👍
