### ISSUE TITLE
The default value of power

### ISSUE THREAD

**Issue by majunkang** [vieira/homebridge-yeelight-wifi#16]
Both in code and config.json, you set the default value of power to `400`. It should be `1`, right?

 `power: (this.transitions && this.transitions.power) || 400,`
```
"transitions": {
            "power": 400,
```

**Comment by vieira** [comment]
Hello @majunkang,

That is the default duration, in ms, for the transition from off to on and vice-versa. It creates a fade-in/fade-out effect when you turn it on/off.

If you would rather have it immediately turn on/off you can set it to 0.
