### ISSUE TITLE
Yeelight ceiling light temperature

### ISSUE THREAD

**Issue by igrampe** [vieira/homebridge-yeelight-wifi#17]
Doesn't change temperature of ceiling light temperature.
https://www.yeelight.com/en_US/product/luna

**Comment by vieira** [comment]
Hello @igrampe,

When I first wrote the code, Yeelight only had either color bulbs or white bulbs. The white bulbs only supported setting the brightness and had a fixed temperature of 2700K.

I see that they now have some devices and bulbs that are only white but support setting a range of temperatures, although at the moment I don't have any to test, I will try to add support for them and ask for your help to test.

Also if you could post your homebridge logs it would be helpful!

Thanks!

**Comment by vieira** [comment]
BTW in the home app, when you open the device, it shows two buttons on the bottom of the screen, details on the right and on the left do you have "color"?

If you click on details and scroll down, what "Model" do you see?

Thanks!

**Comment by rrroyal** [comment]
It all says Default-Manufacter, Default-SerialNumber etc..

**Comment by vieira** [comment]
I will release a version with support for this in the next day or so. You may need to remove the cachedAccessories file and reboot homebridge after updating.

**Comment by vieira** [comment]
I have just released a beta version with color temperature support. It can be installed with `npm install -g homebridge-yeelight-wifi@beta`.

The file `accessories/cachedAccessories` **must be removed** before starting the new version.
