### ISSUE TITLE
default Value name

### ISSUE THREAD

**Issue by theo-69** [vieira/homebridge-yeelight-wifi#18]
Is it possible to ad the default name in config?

Like:

```
"defaultValue": {
            "aed78s": {
                "name": "bed side lamp"
                      }
        }
```

**Comment by vieira** [comment]
Hello,

Currently this is not supported but I might consider adding this in the future. Are you having any problems after setting the name in the Home app?

Thanks!

**Comment by theo-69** [comment]
would be just easier if there are any chances in my homebridge and I have to re add my 10 lamps

**Comment by banzalik** [comment]
https://github.com/vieira/homebridge-yeelight-wifi/pull/23

**Comment by banzalik** [comment]
+1

**Comment by vieira** [comment]
This will be on next release thanks to @banzalik!

**Comment by HonzaaD** [comment]
defaultValue is not working, why? :(

**Comment by banzalik** [comment]
Not relised yet

**Comment by banzalik** [comment]
@vieira can you deploy to NPM 1.0.6 version?
