### ISSUE TITLE
Support Tunable White bulb

### ISSUE THREAD

**Issue by SebDominguez-zz** [vieira/homebridge-yeelight-wifi#28]
Hi,
I have some YLDP05YL, and it would be great that in HomeKit the color switcher is disabled for that type of bulb and only show the color temperature wheel.

**Comment by vieira** [comment]
I will release a version with support for this in the next day or so. You may need to remove the cachedAccessories file and reboot homebridge after updating.

**Comment by vieira** [comment]
I have just released a beta version with color temperature support. It can be installed with `npm install -g homebridge-yeelight-wifi@beta`.

The file `accessories/cachedAccessories` **must be removed** before starting the new version.
