### ISSUE TITLE
Can't set yeelight's name with config.json using defaultValue property

### ISSUE THREAD

**Issue by SebDominguez-zz** [vieira/homebridge-yeelight-wifi#29]
Hi,

I'm trying to set my lightbulb name directly using the config.json

I'm guessing this is the purpose of the `"defaultValue"`thing, the readme isn't really clear about that.

so this is my config file:

```json
{
    "bridge": 
    {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "123-45-678"
    },
    
    "description": "Home project",

    "platforms":
    [
        {
            "platform": "mqtt",
            "name": "mqtt",
            "url": "mqtt://127.0.0.1",
            "port": "1883",
            "topic_type": "multiple",
            "topic_prefix": "homebridge",
            "qos": 1
        },
        {
            "platform": "yeelight",
            "name": "Yeelight",
            "transitions": {
                "power": 400,
                "brightness": 400
            },
            "defaultValue": {
                "3a38f6": {
                    "name": "Test room"
                }
            }
        }
    ]
}
```

**Comment by kelvinyasu** [comment]
It seem the npm not update to 1.0.6 version yet in https://www.npmjs.com/package/homebridge-yeelight-wifi

Can @vieira help to push a update to npmjs please? Many Thank on that..

**Comment by kelvinyasu** [comment]
btw @SebDominguez   you can do install latest version by 
```
npm install git+https://github.com/vieira/homebridge-yeelight-wifi.git
```

However I found the defaultValue can map the device but seem it still not working with the Automation... every time when I restarted the homebridge,  Automation mapping with defaultValue device gone..

**Comment by vieira** [comment]
Sorry for the long delay guys, I have not had much time lately but I will push some updates and create a new release in the next day or so that includes this.

**Comment by vieira** [comment]
I have just released a beta version that includes this feature and color temperature support. It can be installed with `npm install -g homebridge-yeelight-wifi@beta`.
