### ISSUE TITLE
Cant put lights in full brightness after change to some color and come back to temperature

### ISSUE THREAD

**Issue by bgoncal** [vieira/homebridge-yeelight-wifi#34]
The result is that the brightness is 100% in the app but the lamp is only 50%

**Comment by vieira** [comment]
Hello @cpvbruno,

Unfourtunately this is a issue with the firmware after an update from Yeelight, so there is really nothing we can do about it:

https://forum.yeelight.com/t/topic/8594

https://forum.yeelight.com/t/topic/11026
