### ISSUE TITLE
Plugin not working when config.json in /var/homebridge/ ?

### ISSUE THREAD

**Issue by hartmood** [vieira/homebridge-yeelight-wifi#38]
My config.json is not in the default folder. Might this be the reason that I do not see devices coming up? (see [https://timleland.com/setup-homebridge-to-start-on-bootup/]()

I saw other plugins working with "homebridgeDirectory": "/path/to/config.json key/value pair to the platform config.

**Comment by vieira** [comment]
Hello @hartmood,

I believe the plugin would work even without any `config.json`, can you check if there are any errors in the homebridge log?

Thanks!

**Comment by hartmood** [comment]
Thanks for following up
`Jul 10 13:07:24 openHABianPi homebridge[8568]: [7/10/2019, 1:07:24 PM] [Yeelight] doing a round of proactive search for known devices.

Jul 10 13:07:24 openHABianPi homebridge[8568]: [7/10/2019, 1:07:24 PM] [MiAqaraPlatform] [INFO]Aqara LAN protocol server is listening on port: 9898

Jul 10 13:07:24 openHABianPi homebridge[8568]: [7/10/2019, 1:07:24 PM] Homebridge is running on port 51826.

Jul 10 13:07:39 openHABianPi homebridge[8568]: [7/10/2019, 1:07:39 PM] [Yeelight] all known devices found, stopping proactive search.
`
I can find no errors. Although it states to have found all devices none of them pop up in the iOS Home app. I have two Yeelight ceiling lights that are connected through openHAB - so API is open. As far as I understand your plugin correctly the bulbs should appear instantly which they don't do.

**Comment by vieira** [comment]
Hello @hartmood,

If the lamps are new to the plugin, i.e., it never saw them before, that message is OK. The bulbs will advertise themselves on the network and the plugin should then add them. From that moment on they become "known devices".

If after some time they still do not appear and nothing appears on the logs then make sure that the raspberry pi and the bulbs are on the same network and that multicasting is allowed.

**Comment by hartmood** [comment]
UPnP is activated on my Router and I just have one network. I also did a reboot and additionally a restart of the homebridge. But even after two hours nothing has happened yet.

**Comment by vieira** [comment]
Hmm, I can’t think of anything else right now that could cause this. What are the IPs of the ceiling light and of the rpi running homebridge?

**Comment by hartmood** [comment]
OK, I will try to evaluate further after my holidays. Thanks for your help.
