### ISSUE TITLE
Controle two lights of the same ceiling light

### ISSUE THREAD

**Issue by trineu** [vieira/homebridge-yeelight-wifi#40]
Hello! First of all, thanks for the great plugin!

There are some Yelight ceiling lights that have two lights. One with temperature control and one with RGB color control.

Could this plugin control these two lights of the same equipment?

The model I own is this:
https://www.banggood.com/Yeelight-LED-Smart-Meteorite-Chandelier-Pendant-Light-For-Restaurant-Dinner-Room-Xiaomi-Ecosystem-Product-p-1416328.html?akmClientCountry=BR&rmmds=search&cur_warehouse=CN

But I know that there is this too:
https://www.banggood.com/Yeelight-JIAOYUE-YLXD02YL-650-Surrounding-Ambient-Lighting-LED-Ceiling-Light-WiFi-bluetooth-Xiaomi-Ecosystem-Product-p-1362173.html?rmmds=search&ID=557324&cur_warehouse=CN

**Comment by alialrahma** [comment]
Any HomeKit lightbulb can be grouped and controlled together. That is through Home > select Settings to accessory > then Group.

**Comment by jakaZ0806** [comment]
That's not what he's talking about. This is one lamp, reachable at one single IP-Adress, that has a downward-facing white light with color temperature and one upward-facing "ambient" light with rgb colors; these can be controlled individually.
I'm not sure which commands control which part of the light, but i'd be willing to help test it out.

**Comment by alialrahma** [comment]
My bad, I didn’t go through the photos fully and thought he meant to control both lights from the links he posted. 

Very interesting lights - look forward to see you helping him make it work and maybe I’ll grab one then for my kitchen.

**Comment by jakaZ0806** [comment]
Hi! I found out all commands to control the background light. But I don't have much time on my hands right now and I'm switching to openHAB anyways. I'm in the process of adding support to their yeelight plugin if anyone is interested. The openHAB items can be imported in homebridge as well. The basic features are (almost all) working. [Repository Link](https://github.com/jakaZ0806/openhab2-addons/tree/master/bundles/org.openhab.binding.yeelight)
Meanwhile, I'll share my findings here if anyone (or me in the future) is starting to implement direct support for homebridge:
- [Yeelight API Doc](https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf)
- basically, all methods and params of the ambient light are prefixed with bg_
- Homekit does not support custom devices, so the light has to be configured as two lights in homekit (one with color temperature and one with colors)
- As of now, as I got from quickly glancing at the code, the connection handler of this addon can't connect to the same device twice. So in case there also will be two separate instances in this addon, the connection handler has to be rewritten (maybe as external service and not in each device's code). Or a new device type has to be created which registers as two homekit devices. Someone should look at this closer though, as I only looked briefly.

**Comment by boro55** [comment]
@jakaZ0806 Hi! Any chance you made any progress with direct support for the Yeelight Meteorite?

**Comment by jpawlowski** [comment]
+1

**Comment by jakaZ0806** [comment]
> @jakaZ0806 Hi! Any chance you made any progress with direct support for the Yeelight Meteorite?

I did not (and do not intend to in the future) continue investigating this since the light is working perfectly with the updated openHAB yeelight plugin and the openHAB-homebridge-complete plugin for homebridge support.
Sorry for all that were hoping for an update here.

**Comment by vieira** [comment]
Initial support for controlling power, brightness and the color of the backlight (also known as ambilight) of devices that have it is now in 3.0.0-beta.0. 🎉 

As I don't have a lamp that supports it I would be relying on you to let me know if everything is working as expected!

Please note that 3.x requires node >= 16.16 and homebridge >= 1.3.0.
