### ISSUE TITLE
Every plugin becomes unresponsive when a Yeelight is down

### ISSUE THREAD

**Issue by robpegurri** [vieira/homebridge-yeelight-wifi#42]
Hello,

First of all I'd like to congrats for your job, this plugin is really amazing! 

However, I was obliged to switch to the old buggy homebridge-yeelight plugin because it seems that your plugin slows down every other plugin when a light is disconnected.

In fact, when a light is turned of by the wall switch, every home bridge plugin shows "updating" after a while... that really sucks especially when connecting from out of home, it takes literally 10 minutes to connect to my accessories (obviously no problem with my Hue bridge as it responds immediately even if every other homebridge accessory is updating).

I hope you will help me solving this issue, I really loved your job! At least let me know if there is a parameter to add in the config.json in order to fix this issue (even if losing some feature).

Thanks in advance!
Rob

**Comment by RealDyllon** [comment]
You might want to increase the connection timeout to a higher value.

**When i increased it from 100 to 250**, my homebridge became more stable.

If you really want to increase performance, the best thing would be to use multiple homebridge instances; one for each platform and each accessory.

**Comment by okonet** [comment]
Related to #61

**Comment by vieira** [comment]
This can now be resolved by using hombridge [child bridges](https://github.com/homebridge/homebridge/wiki/Child-Bridges).
