### ISSUE TITLE
Official Yeelight HomeKit support

### ISSUE THREAD

**Issue by iChUdY** [vieira/homebridge-yeelight-wifi#43]
Does this plugin still make sense when i existing yeelight bulbs got official homekit support after firmware upgrade? Now...

**Comment by diogoterremoto** [comment]
It appears that the first version of Yeelight doesn't have HomeKit support, so yes.

**Comment by iChUdY** [comment]
This https://www.gearbest.com/smart-lighting/pp_1664464.html now official support HomeKit.

**Comment by diogoterremoto** [comment]
That's the second version (has a white shell). The first version (with a silver shell) doesn't support HomeKit.

**Comment by rrroyal** [comment]
Also, default HomeKit support is pretty much useless - after restarting HomeKit on controlling device, bulbs no longer respond.

**Comment by iChUdY** [comment]
@rrroyal in not my case...

However, the main reason is that the official homekit support suffers from the same CT defect and the lamp shade control shines only at "80%" brightness. Incredible fail.

**Comment by IGI2** [comment]
Okay, guys! I think we've established the answer to the main question of this issue:
_"Does this plugin still make sense"_

**Yes, this plugin makes sense.**

Can we close the issue now?
