### ISSUE TITLE
Moonlight support on LED Ceiling Light

### ISSUE THREAD

**Issue by Arderos** [vieira/homebridge-yeelight-wifi#46]
Hi!
Yeelight LED Ceiling Light (identified by the plugin as "ceiling4") has an awesome feature called "Moon" or "Moonlight". It basically dims the main light way lower than in any other mode and leaves the Ambilight on.
Any chance this feature will be supported?

**Comment by boro55** [comment]
Plus it'd be awesome to have the main light and ambilight to show up as a two separate devices in Homekit.

**Comment by Homebridge1986** [comment]
Unfortunately can ‘t find plugin to enable moonlight feature for ceiling yeelight lamps :(

**Comment by jpawlowski** [comment]
I thin the same thing (or at least similar) is true for [YeeLight Crystal Pendant Lamps](https://www.yeelight.sg/yeelight-crystal-led-pendant-lamp) `ceilling10`. Not sure how you would control the upwards color effect light, probably it is just different to discover and needs to be exposed as a second lamp with color capability only.

**Comment by okonet** [comment]
I've just implemented support for moonlight mode in #49. I'll add support for backlight as soon as a lamp of that kind arrives :)

**Comment by slcr** [comment]
your branch works great, also a nifty solution 👍 

Some things i noticed though:
- there's a lot of logging happening for just simple tasks. This is disabling Moonlight Mode and changing brightness
```
[Homebridge] [12/10/2019, 7:25:39 PM] [Yeelight] Setting ☀️ mode on device 0x00000000066a4495
[Homebridge] [12/10/2019, 7:25:39 PM] [Yeelight] {"method":"set_power","params":["on","smooth",120,1],"id":426}
[Homebridge] [12/10/2019, 7:25:39 PM] [Yeelight] warn failed attempt 0 after 100ms.
[Homebridge] [12/10/2019, 7:25:39 PM] [Yeelight] {"method":"set_power","params":["on","smooth",120,1],"id":426}
[Homebridge] [12/10/2019, 7:25:39 PM] [Yeelight] warn failed attempt 1 after 200ms.
[Homebridge] [12/10/2019, 7:25:39 PM] [Yeelight] {"method":"set_power","params":["on","smooth",120,1],"id":426}
[Homebridge] [12/10/2019, 7:25:40 PM] [Yeelight] active_bright is not supported in Homekit, skipping.
[Homebridge] [12/10/2019, 7:25:40 PM] [Yeelight] nl_br is not supported in Homekit, skipping.
[Homebridge] [12/10/2019, 7:25:40 PM] [Yeelight] { id: 426, result: [ 'ok' ] }
```
- It's a bit laggy when opened the first time. Seems like it get's better over time, but when i opened the devices for the first time there was an empty layer for 1-2 seconds and then the slider/switch popped up. 

I'll play around more with it, we'll see how everything works out with automations etc.

Tested Devices:
2x Yeelight YLXD41YL (320mm with native homekit)
2x Yeelight YLXD50YL (470mm with native homekit)
1x Yeelight Meteorite Crystal Pendant Light (no native homekit)

as homekit does not support moonlight mode, this is an awesome addition <3

**Comment by okonet** [comment]
I only added one addition log for the node switch so feel free to tidy it up.
