### ISSUE TITLE
Scan on multiple subnets

### ISSUE THREAD

**Issue by luci84tm** [vieira/homebridge-yeelight-wifi#5]
Hi there,

is it possible that your plugin scann for yeelight bulbs in different subnets?
I do have my bridge in 192.168.1.0/24 but the bulbs are in 192.168.10.0/24

or can I add accessories manually into some config file, so that it points to different ip address?

Thanks!

**Comment by vieira** [comment]
Hello @luci84tm,

Would the issue reported on #8 also apply to you? If so do you think #9 would solve it for you?

Thanks!
