### ISSUE TITLE
Yeelight Meteorite Table Pedant Light - Problems with Moonlight Mode

### ISSUE THREAD

**Issue by IGI2** [vieira/homebridge-yeelight-wifi#51]
Hello guys!

Despite the latest addition of support for Moonlight effect, this lamp still misbehaves:
![IMG_1296](https://user-images.githubusercontent.com/39410473/70577958-a97ba900-1bac-11ea-844a-6f971714cd66.jpeg)

I have Xiaomi Yeelight Meteorite and the switch does not work.

https://streamable.com/pxzh0
https://streamable.com/rmum4

The switch does not control "the moonlight".

Logs: https://pastebin.com/uk2HzGFT
More logs: https://pastebin.com/GLSGE3v8

**Comment by okonet** [comment]
I believe this is a lamp with active and background lights which I didn’t add support to yet. I’m still waiting for my lamp to arrive after that I can work on the integration for the backlight.

**Comment by IGI2** [comment]
Okay. 

So when you do integrate it, just please set the type of the "switch" to RGBW light as well. And you can still utilize the HomeKit feature to show it as a one device. After all, anyone can click "show it as Separate Tiles" ;) 

If you want I can provide some logs.

**Comment by okonet** [comment]
I don't believe one can have switch with light bulb settings. Not sure how you're imaging it. Feel free to implement yourself and submit a PR.

**Comment by tobeehh** [comment]
@okonet 

i am very new to coding but am also very interested in the backlight feature in the ceiling10 lamp.

Someone already gave some hints how to integrate:
https://github.com/vieira/homebridge-yeelight-wifi/issues/40#issuecomment-519630677

Maybe this can help.

**Comment by okonet** [comment]
I’ll be implementing it as soon as I get the lamp myself.

**Comment by paqpaqpaq** [comment]
Can moonlight function be switched off until then?
This is a really annoying feature this way. (the extra switch)

nvr mnd: Made it separate tiles and hid them.

Ambilight function would still be nice anyway ;)

**Comment by okonet** [comment]
Please upgrade the plugin. It should appear for your lamp anymore.

**Comment by paqpaqpaq** [comment]
> Please upgrade the plugin. It should appear for your lamp anymore.

well, it actually did because of the update...

**Comment by okonet** [comment]
What’s the model name of your lamp. I made the plugin only add moonlight mode for ceiling and lamp but maybe my check is incorrect. Unfortunately Yeelight does not give a reliable way of checking of that feature.

**Comment by paqpaqpaq** [comment]
> What’s the model name of your lamp. I made the plugin only add moonlight mode for ceiling and lamp but maybe my check is incorrect. Unfortunately Yeelight does not give a reliable way of checking of that feature.

the 'meteorite'
"Yeelight ceiling10"
Also saw it as "crystal"

**Comment by Igor29** [comment]
> I’ll be implementing it as soon as I get the lamp myself.

Hi! I see you did some refactoring 🙂 but did you get the lamp? Have you looked into it?

**Comment by okonet** [comment]
@Igor29 no, there is no progress since there is no lamp. But you could try implementing it and not wait for me :)

**Comment by okonet** [comment]
@paqpaqpaq so you’re saying that for this lamp there is no moonlight mode available? That’s sucks since the documentation says all ceiling lights have it. Basically makes my check unreliable. I can provide a way to disable this feature in the config I think.

**Comment by paqpaqpaq** [comment]
@okonet It more or less works.
But as is, it is almost impossible to handle, because simply tapping the tile does nothing. So if you separate the tiles (moonlight switch and lamp) the lamp functions as should again. 
If I flip the moonlight switch the moonlight function works. However, when I switch the moonlight function off again, the lamp goes back to its previous brightness in real life, but the dimmer claims it is 1%.

**Comment by okonet** [comment]
Okay so the lamp has the moonlight mode. That’s most important thing. I’ll investigate the behavior you’re seeing since I can se it with my floor lamp too. Ceiling lights function well, though.

**Comment by markaragnos81** [comment]
hi there. thanks for your great work so far. are you planning to integrate the upward-facing "ambient" light with rgb colors ?

**Comment by tobeehh** [comment]
@markaragnos81 please read this thread. He is planning to implement this once he received the lamp.

**Comment by migabc** [comment]
Hi,
Did you receive the lamp?
Were you able to to integrate the upward-facing "ambient" light (aka, moonlight) as dimmable lights with RGB colors independent from the downward facing light?

**Comment by okonet** [comment]
I did receive it but wasn’t able to find time to work on it. Feel free to try it yourself.

**Comment by paqpaqpaq** [comment]
any news on this one?

**Comment by vieira** [comment]
Initial support for controlling power, brightness and the color of the backlight (also known as ambilight) of devices that have it is now in 3.0.0-beta.0. 🎉

As I don't have a lamp that supports it I would be relying on you to let me know if everything is working as expected!

Please note that 3.x requires node >= 16.16 and homebridge >= 1.3.0.
