### ISSUE TITLE
Cannot read property 'latest' of undefined

### ISSUE THREAD

**Issue by okonet** [vieira/homebridge-yeelight-wifi#53]
In logs I see `[Config] [homebridge-yeelight-wifi] Cannot read property 'latest' of undefined`

**Comment by okonet** [comment]
Moved to https://github.com/oznu/homebridge-config-ui-x/issues/427 since I'm not sure it comes from this repo

**Comment by vieira** [comment]
Hmm never saw this one and didn't even find any property `latest` being read by our code.
