### ISSUE TITLE
Siri command "Set to white/red" not working (Siri language: german)

### ISSUE THREAD

**Issue by ghost** [vieira/homebridge-yeelight-wifi#6]
**Precondition:**

- Raspberry Pi 3
- Homebridge installed
- homebridge-yeelight-wifi installed
- yeelight in developer mode
- yeelight working correctly with yeelight app and homekit app
- Siri and iPhone language are german ("Stelle das Licht auf weiß/rot)

**How to reproduce:**

(1. Ask Siri to set the color to green, yellow, blue, orange, violett and turquois)
2. Ask Siri to set the color to white and red

**Result:**
All colors are set correctly, except for white and red

**Expected Result:**
You can set the yeelight to the colors white and red too by using Siri

Can anyone reproduce this behavior?

**Comment by vieira** [comment]
Hello @eikebs,

Thanks for the report and sorry for the delay.

I was able to reproduce the issue, I will try to work on a fix some time this week.

**Comment by vieira** [comment]
Hello @eikebs,

#7 should fix this issue. I will test for a couple of days and release a new version on npm probably on the weekend if everything is fine.

Thanks.

**Comment by ghost** [comment]
Oi João,
thank you very much for your work and effort.
You did a great job with this plugin.

**Comment by vieira** [comment]
Thanks @eikebs,

Published 1.0.3 to npm which should fix this issue.

Thanks for reporting!

**Comment by ghost** [comment]
Thanks @vieira, it's working perfectly.
