### ISSUE TITLE
Unable to use this plugin

### ISSUE THREAD

**Issue by hazrulk** [vieira/homebridge-yeelight-wifi#62]
Hi, I usually am able to use this plugin but it starts to crash and shutting down homebridge. I only have this plugin installed on to my homebridge pi

[12/19/2019, 15:23:24] [homebridge-yeelight.yeelight] doing a round of proactive search for known devices.
[12/19/2019, 15:23:24] Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data
    at Socket.onListenError (dgram.js:507:22)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at dgram.js:322:14
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[12/19/2019, 15:23:24] Got SIGTERM, shutting down Homebridge...

Can anyone please guide me. It was working fine for the past weeks

**Comment by RealDyllon** [comment]
Post your config.json

**Comment by hazrulk** [comment]
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:xx:xx",
		"port": 51826,
		"pin": "031-45-xxx"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
	"ports": {
		"start": 52100,
		"end": 52150,
		"comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
	},
	"accessories": [],

	"platforms": [
		{
			"platform": "yeelight",
			"name": "Yeelight",
			"transitions": {
				"power": 400,
				"brightness": 400,
				"color": 1500,
				"temperature": 1500
			},
			"connection": {
				"retries": 5,
				"timeout": 250
			},
			"multicast": {
				"interface": "0.0.0.0"
			},
			"defaultValue": {
				"aed78s": {
					"name": "Kitchen",
					"blacklist": ["set_hsv"]
				}
			}
		}
	]
}

**Comment by RealDyllon** [comment]
Remove the defaultValue object, and give it a try.

**Comment by hazrulk** [comment]
It somehow working fine after 2 days. I am clueless but thanks a lot for the effort to look into my .json file
