### ISSUE TITLE
Ambilight

### ISSUE THREAD

**Issue by mstef** [vieira/homebridge-yeelight-wifi#65]
Hi. I have an "old" YLXD02YL model 650 with Moonlight and Ambilight mode. Thanks to your plugin now I can use Moon mode. I wonder if you can add Ambilight also?

**Comment by pechatny** [comment]
Ambilight mode will be great for me too 👍

**Comment by suzdalini7** [comment]
Ambilight mode will be amazing for my Crystal Pendant Lamp (meteorite) YLDL01YL (ceiling10)

**Comment by lyance** [comment]
Yes, I'm another owner of Crystal Pendant Lamp (meteorite) YLDL01YL (ceiling10) -- would be great to have Ambilight supported.

**Comment by Ivanovitchk** [comment]
guys, a quick hack to enable the ambilight (only change it's color, cannot turn it on/off or change it's brightness, eg it needs to be on already by the app or remote / wallswitch)

ssh into your box and in **./platform.js**

change `if (features.includes('set_hsv')) ` to `if (features.includes('bg_set_hsv')) `

and in **./bulbs/color.js**

change `method: 'set_hsv'` to `method: 'bg_set_hsv'`


**warning** if you have multiple yeelight bulbs / lamps, you will lose RGB control on non-ambilight ones (eg the bulbs which don't have an ambilight but do support RGB on their main -and only- output)


I might submit a PR to add this feature properly, if I find time :D

**Comment by Mimomaj** [comment]
Hello @Ivanovitchk , could you please advise where I can find the mentioned js files? (My HB is running on Pi4)

**Comment by vieira** [comment]
Initial support for controlling power, brightness and the color of the backlight (also known as ambilight) of devices that have it is now in 3.0.0-beta.0. 🎉

As I don't have a lamp that supports it I would be relying on you to let me know if everything is working as expected!

Please note that 3.x requires node >= 16.16 and homebridge >= 1.3.0.
