### ISSUE TITLE
V3 Yeelight Bulb

### ISSUE THREAD

**Issue by josehipo** [vieira/homebridge-yeelight-wifi#69]
Hi!

I just added a V3 bulb (Homekit compatible) to my home and I can't find a way to avoid being discovered and connected by homebridge-yeelight-wifi except to disable LAN control, which will make the V3 bulb less sensitive and slower.

I guess there must be a simple way to do it, but I couldn't find it.
Thank you.

**Comment by vieira** [comment]
As of 2.4.0 you can ignore a light by setting `blacklist` to `true`, e.g.:

```
{
  "bridge": {
    "name": "Raspberry Pi"
  },
  "accessories": [{}],
  "platforms": [
    {
      "platform": "yeelight",
      "name": "Yeelight",
      "defaultValue": {
        "aed78s": {
          "blacklist": true
        }
      }
    }
  ]
}
```
