### ISSUE TITLE
Detecting Moonlight for Mi LED Desk Lamp

### ISSUE THREAD

**Issue by seanzhang98** [vieira/homebridge-yeelight-wifi#73]
Hi，

My Mi LED Desk Lamp (first version) is not support moonlight mode but the log gives me 

[4/25/2020, 22:20:51] [Yeelight] Device lamp1-f6db90 supports moonlight mode
[4/25/2020, 22:20:51] [Yeelight] Device lamp1-f6db90 supports brightness
[4/25/2020, 22:20:51] [Yeelight] Device lamp1-f6db90 supports color temperature

the moonlight mode switch is useless for my device and it is kind of  annoying :( 
Any way to fix it or disable moonlight mode form config in homebridge?

Thx ;)

**Comment by Jafalex** [comment]
Hey @seanzhang98 , sorry to reopen an old thread but I have the same Mi LED Desk Lamp and I'm unable to see it in HomeKit, I've tried this plugin and many others. I'm sure my token is the right one (followed the exact steps). 
Is yours still working with this plugin? Anything you've done in particular? 
Thanks!

**Comment by seanzhang98** [comment]
hi @Jafalex , mines is working properly for a while, noting specific steps are required. I personally made some modification of the codes so the moonlight function will not shown in Home app. ￼
