### ISSUE TITLE
Problems with color change (ceiling1-f5a631)

### ISSUE THREAD

**Issue by skelurr** [vieira/homebridge-yeelight-wifi#78]
Hello,

I have the following lamp ceiling1-f5a63. I can control them with the plug-in, unfortunately I cannot change the color of the lamp.
Has anyone already solved the problem?

**Comment by elmoritz** [comment]
Hello,
I might have the same Problem, but your Device name doesn't really help.
The model I have (according to the Yeelight App) is yeelink.light.ceiling20, which has 2 different lights.
1. main light (no color just a range from yellow-ish to white)
2. an ambient light ring, which can be set to basically any color

As far as I can tell there is no option to set the color of the second one.

**Comment by vieira** [comment]
Initial support for controlling power, brightness and the color of the backlight (also known as ambilight) of devices that have it is now in 3.0.0-beta.0. 🎉

As I don't have a lamp that supports it I would be relying on you to let me know if everything is working as expected!

Please note that 3.x requires node >= 16.16 and homebridge >= 1.3.0.
