### ISSUE TITLE
Specify network interface for multicast

### ISSUE THREAD

**Issue by LucaTNT** [vieira/homebridge-yeelight-wifi#8]
Hi, thanks for this plugin!

I have a little problem that I managed to solve with a quick and dirty edit, but I think it could deserve a more robust solution.

Basically my Homebridge machine has two network interfaces: eth0, which is connected to my main LAN (iOS devices and Apple TV are here), and sorv0, which is my IOT subnet, where my Yeelights are.

Multicast packets seem to prefer eth0 (which is the one with the default gateway, btw), while I need them to go through the other interface.

My solution was to edit platform.js adding this just after line 26
`this.sock.setMulticastInterface("192.168.30.30");`

That IP address is the one on the sorv0 IOT interface.

I also developed a better solution that gets the IP of the given interface, to make it able to withstand changing IP addresses on the interface, but my problem is that I have to hardcode the address/interface name in the platform.js file, I can't seem to pass any parameters from Homebridge's config.json to this plugin.

Any hint?

Thanks

Luca

**Comment by vieira** [comment]
Hello @LucaTNT,

#9 should address this by making the multicast network interface configurable via:

```json
{
    "platforms": [{
        "platform": "yeelight",
        "name": "Yeelight",
        "multicast": {
            "interface": "0.0.0.0"
        }
    }]
}
```

Is this fine with you?

Thanks!

**Comment by LucaTNT** [comment]
Looks great!

**Comment by vieira** [comment]
Hello @LucaTNT 

This is now part of 1.0.4.

Best regards!
