### ISSUE TITLE
Doesnot connects to Yeelight Lightstrip Plus

### ISSUE THREAD

**Issue by kaushikdas0** [vieira/homebridge-yeelight-wifi#80]
I have several Yeelight devices and managed to connect to most, other than the Lightstrip Plus. Can you please add support for this. 

Appreciate the work. Thanks

**Comment by mstef** [comment]
I have three Yeelight Lighstrip Plus and all work. Have you enabled „LAN Control” for them in Yeelight app?

**Comment by kaushikdas0** [comment]
Hi @mstef , thanks. this is working with Lan Control. Thanks a lot.
