### ISSUE TITLE
Hide Moonlight tile

### ISSUE THREAD

**Issue by Trippersgarage** [vieira/homebridge-yeelight-wifi#81]
Apologies if this has been posted somewhere, I've searched but I didn't see any actual instructions. Is it possible to hide the "moonlight mode" tile in the home app? Thank you!

**Comment by vieira** [comment]
Hello, this should now be possible in **3.0.0-beta.0**.

When homebridge starts you should see something like this in your logs:

```
Device color-5c4bc1 supports moonlight mode
```

Edit the `config.json` and add the following block (**replace** `5c4bc1` with the id of your device) and restart homebridge.

```
"platforms": [
  {
    "platform": "yeelight",
    "name": "Yeelight",
    "defaultValue": {
      "5c4bc1": {
        "blacklist": ["active_mode"]
      }
    }
  }
]
```

**Note**: It might happen that the device is already cached and this change does not reflect in the Home app. In that case set `"blacklist": true` and restart homebridge. The device should disappear from the Home app. After that repeat the steps above.

Let me know if it works.
