### ISSUE TITLE
Request: An ability to "Blacklist" devices

### ISSUE THREAD

**Issue by BaRaD5** [vieira/homebridge-yeelight-wifi#82]
Hey, thanks a bunch for this plugin! 
Something I'd like to see added is an option to have a black list or a white list to either not show (black list) or show only (whitelist) Specific devices... 
This is to kill "duplicates" problem with supported homekit bulbs showing up twice (using this plugin and yeelight official int.)

thank you.

**Comment by irusland** [comment]
Hello! Any updates on this?

**Comment by vieira** [comment]
As of 2.4.0 you can ignore a light by setting `blacklist` to `true`, e.g.:

```
{
  "bridge": {
    "name": "Raspberry Pi"
  },
  "accessories": [{}],
  "platforms": [
    {
      "platform": "yeelight",
      "name": "Yeelight",
      "defaultValue": {
        "aed78s": {
          "blacklist": true
        }
      }
    }
  ]
}
```
