### ISSUE TITLE
Ignore 

### ISSUE THREAD

**Issue by K2i4n6g8** [vieira/homebridge-yeelight-wifi#86]
First, Thank so much for this amazing plugin
Then if you could add to the configurations that you could ignore the light you want
And thank you again for your hard work

**Comment by ichasecorals** [comment]
I would also like this feature. I have 3 bedside lamps that have official HK support. But this plugin also see it and adds to HK.

**Comment by mstef** [comment]
Guys, did you set disable „LAN Control” in Yeelight app for these lamps with native HomeKit?

**Comment by ichasecorals** [comment]
> Guys, did you set disable „LAN Control” in Yeelight app for these lamps with native HomeKit?

Yeelight app doesn't allow me to toggle the LAN CONTROL. One is stuck at OFF and 2 are stuck at ON. But the one that is stuck at off still show in HK and in HOOBS

**Comment by FTHS92** [comment]
Hello Guys,
is there still no way to ignore a light? I have a mixed setup with HK supported and not supported devices.
I don't want to turn off the LAN Control because it's slower to respond with Google Home and the Yeelight app. See here: [https://forum.yeelight.com/t/topic/15354](url)
I would really appreciate if someone could implement that feature.

**Comment by vieira** [comment]
As of 2.4.0 you can ignore a light by setting `blacklist` to `true`, e.g.:

```
{
  "bridge": {
    "name": "Raspberry Pi"
  },
  "accessories": [{}],
  "platforms": [
    {
      "platform": "yeelight",
      "name": "Yeelight",
      "defaultValue": {
        "aed78s": {
          "blacklist": true
        }
      }
    }
  ]
}
```

**Comment by neekchan** [comment]
> As of 2.4.0 you can ignore a light by setting `blacklist` to `true`, e.g.:
> 
> ```
> {
>   "bridge": {
>     "name": "Raspberry Pi"
>   },
>   "accessories": [{}],
>   "platforms": [
>     {
>       "platform": "yeelight",
>       "name": "Yeelight",
>       "defaultValue": {
>         "aed78s": {
>           "blacklist": true
>         }
>       }
>     }
>   ]
> }
> ```

Hello,

What do I replace "ae78s" with? Do i add serial number of the device? or what? I'm a little confused and am not a coder but am trying to not have duplicate lights in my homekit.

**Comment by vieira** [comment]
In your logs you will have some lines like:

```
[Yeelight] Received advertisement from ae78s.
[Yeelight] Device ceiling3-ae78s supports brightness
```

Replace the `ae78s` with whatever shows in your case.
