### ISSUE TITLE
Bulb 1S communication setup help

### ISSUE THREAD

**Issue by vskal** [vieira/homebridge-yeelight-wifi#88]
Hello and thanks for the work on this plugin !

I have a "Yeelight smart LED bulb 1s" already connected to Homekit the easy way, by scanning the code in the manual.

I also installed this mode (with the optional configuration) trying to learn more with my homebridge located in a QNAP NAS container. 

The lamp seems to communicate at start:
[yeelight] Received advertisement from 602bbb.
[yeelight] Device color4-602bbb supports brightness
[yeelight] Device color4-602bbb supports color temperature
[yeelight] Initialized device  (192.168.1.XX:55443).
[yeelight] Received advertisement from 602bbb.

but then I get:
[yeelight] 192.168.1.XX closed. error? false.
[yeelight] 0x0000000015602bbb: failed communication attempt 5 after 3200ms.
[yeelight] 0x0000000015602bbb: failed to send cmd 1 after 5 retries.

Could a conflict be the reason for this behaviour? I mean having 2 instances of the same lamp appearing in homekit ? 
or/and
Am I missing avahi and Node.js ? Are they installed automatically with the plugin or do I have to do it ?  
How can I install them in a NAS container please?
or/and
Do I need to use a multicast value other than 0.0.0.0 like in your example ?
I used my lamps ID in "defaultValue": {
        "aed78s":

I also have a couple of "Mi smart LED Bulb Essential" which are also from Xiaomi, is there a chance that the plugin will detect them?

Any advice would be appreciated because, as you can guess, I am quite confused.

Many thanks !

**Comment by Alex-Mazikin** [comment]
Hi. I have the same problem but I am not using native HomeKit support (White brightness problem).
Mostly working well, but time to time I have the same logs with connection error and communication attempts.

**Comment by vskal** [comment]
I found out that if you power off the lamp and on again (from the switch) it resets and communication resumes.

**Comment by jackscorpse** [comment]
Don’t know how it works, but yesterday I tried many times to install and remove plugin, reset bulb, reboot homebridge. Now the plugin is stable even after homebridge reboot. I use a default  configuration. I noticed that after changing the config, there are errors, so for now I've left everything as it is.
