### ISSUE TITLE
2.30 with adaptive lighting broke color temp change

### ISSUE THREAD

**Issue by rrusli01** [vieira/homebridge-yeelight-wifi#90]
Hi,

Since the update I can't change the temperature of all my ceiling lights unless I turn on and off moonlight mode every time.

This error message comes up:
Received warning for the plugin 'homebridge-yeelight-wifi' from the characteristic 'Color Temperature': SET handler returned write response value, though the characteristic doesn't support write response!

Im using homebridge 1.3.0 beta.57 and yeelight 2.30 

Looking forward to using the adaptive lighting.

Thanks!

**Comment by rrusli01** [comment]
further error details from debug mode:
Error: 
    at ColorTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2063:79)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1618:22
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at ColorTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge-yeelight-wifi/bulbs/temperature.js:21:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by hotdotdev** [comment]
Get the same message.

**Comment by okonet** [comment]
It should be fixed now as per https://github.com/vieira/homebridge-yeelight-wifi/releases/tag/v2.3.1
