### ISSUE TITLE
Sending search request...

### ISSUE THREAD

**Issue by hbkmanbass** [vieira/homebridge-yeelight-wifi#91]
Dear users, 

When I install the plugin everything seems to work. But when I restart the raspberry pi just one time, it don't work anymore. 
I have a Yeelight strip wifi with the LAN mode activate. 

When i restart the raspberry pi I get an endless [yeelight] Sending search request... 

Thanks in advance for your help,

**Comment by fupzlito** [comment]
I have the same issue, my lightbulbs don't get discovered unless I turn LAN control off and then on again in the Yeelight app. 
I didn't have this issue before, it only appeared after updating the plugin about a month ago

**Comment by javier-de-juan** [comment]
Hello! What version of Homebridge do you have? Since version 1.3.x was released a short time ago, many plugins had to be updated to ensure compatibility. Maybe it is related to a version <1.3.x installed?

**Comment by fupzlito** [comment]
> Hello! What version of Homebridge do you have? Since version 1.3.x was released a short time ago, many plugins had to be updated to ensure compatibility. Maybe it is related to a version <1.3.x installed?

**Comment by fupzlito** [comment]
> Hello! What version of Homebridge do you have? Since version 1.3.x was released a short time ago, many plugins had to be updated to ensure compatibility. Maybe it is related to a version <1.3.x installed? 

Hi, I actually forgot to post an update here, I tried using an old version of the plugin, and I still had the same issue. Then I tried using and older version of Homebridge, and everything worked fine. 
So yeah, I think the problem is related to the newer versions of Homebridge (1.3 and up).

**Comment by roxxov** [comment]
Have the same problem with the 1.3.4 version of Homebridge. Then it is probably waiting for an update...

**Comment by hbkmanbass** [comment]
> I have the same issue, my lightbulbs don't get discovered unless I turn LAN control off and then on again in the Yeelight app.
> I didn't have this issue before, it only appeared after updating the plugin about a month ago

Thanks for the tip ! 

Still add the problem ... can we have an update ?

**Comment by the3future** [comment]
I have downgraded to v1.2.5 of Homebridge. 

Hope this is going to be fixed soon

**Comment by vieira** [comment]
I tried to reproduce this with homebridge 1.6.1 and it seems it's no longer happening? If it's still happening please reopen and let me know which steps should I take to reproduce.
