### ISSUE TITLE
Characteristic Warnings

### ISSUE THREAD

**Issue by reyo** [vieira/homebridge-yeelight-wifi#96]
Just many:

[4/19/2021, 11:41:12 PM] [homebridge-yeelight-wifi] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.

Have Lighstrip Plus, Color bulb v1 and v3.

**Comment by vieira** [comment]
Hello @reyo,

Which version of `homebridge` and `homebridge-yeelight-wifi` are you running?

**Comment by reyo** [comment]
> Hello @reyo,
> 
> Which version of `homebridge` and `homebridge-yeelight-wifi` are you running?

Hi!

I use latest always. Docker version from **oznu/homebridge**. All plugins are latest and every thing that can be, is up-to-date (stuff that has an update button next to it)

**Comment by reyo** [comment]
I can debug more, if needed.

**Comment by vieira** [comment]
Should be fixed in 2.4.0. 👍
